### ISSUE TITLE
[qb-target] Attempt to index a nil value

### ISSUE THREAD

**Issue by bedar89** [CQC-Scripting/cqc-mugshot#6]
Very nice script, but I'm unable to use qb-target with this script. I've followed all instructions, but I keep getting the error `attempt to index a nil value (global QBCore)`.

/testmugshot and /testmugshotself work perfectly.

**Comment by Quinn101** [comment]
Do you use an older version of QB? As we only use the update to method
local QBCore = exports['qb-core']:GetCoreObject()

**Comment by bedar89** [comment]
I'm using the latest QBCore (pulled all the latest updates 2 days ago - every 2 days)

**Comment by Quinn101** [comment]
Can you please message me on discord? Quinn#2329

Makes it easier to debug when we can chat back and forth and share pictures quickly

**Comment by ericb160** [comment]
yea i have the same problem. everything works but the target i get errors

**Comment by Quinn101** [comment]
So it's your qb-target throwing the error? can you screenshot your F8 menu for me? @ericb160
